### ISSUE TITLE
老师能不能写个docker-compose.yml

### ISSUE THREAD

**Issue by sanshilei** [shanlusun/blockchain#1]
写完直接docker-compose up下就好了的那种 我本机环境有docker 不想装vagrant 和 vbox

**Comment by shanlusun** [comment]
fabric的环境不是只需要docker的，很多小的工具依赖可编译的环境，使用vagrant会有很多好处，环境独立便于维护、分享给其他一起开发的同事。
至于docker-compose文件，fabric官方就有写好的：https://github.com/hyperledger/fabric/tree/release/examples/e2e_cli

**Comment by sanshilei** [comment]
谢谢了
